# Generated by Django 2.2 on 2019-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipperrequirement',
            name='requirement_id',
            field=models.IntegerField(default=0),
        ),
    ]
