# Generated by Django 2.2 on 2019-04-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shipperrequirement_requirement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Línea de transporte'), (1, 'Vehículo'), (2, 'Operador')], default=0)),
            ],
        ),
    ]
