# Generated by Django 2.2 on 2019-04-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierlegalcompliance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driverrequirement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicleequipment',
            name='name',
        ),
        migrations.AddField(
            model_name='carrierlegalcompliance',
            name='requirement_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Requirements'),
        ),
        migrations.AddField(
            model_name='driverrequirement',
            name='requirement_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Requirements'),
        ),
        migrations.AddField(
            model_name='vehicleequipment',
            name='requirement_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Requirements'),
        ),
    ]
