# Generated by Django 2.2 on 2019-04-15 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190415_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipperrequirement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shipperrequirement',
            name='required_by',
        ),
        migrations.RemoveField(
            model_name='shipperrequirement',
            name='requirement_id',
        ),
        migrations.AddField(
            model_name='shipper',
            name='requirements',
            field=models.ManyToManyField(default=0, related_name='requirements', through='core.ShipperRequirement', to='core.Requirements'),
        ),
        migrations.AddField(
            model_name='shipperrequirement',
            name='requirement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_requirement', to='core.Requirements'),
        ),
        migrations.AddField(
            model_name='shipperrequirement',
            name='shipper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_requirement', to='core.Shipper'),
        ),
    ]
