# Generated by Django 2.2 on 2019-04-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190415_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='requirements',
            field=models.ManyToManyField(default=0, related_name='legal_requirements', through='core.CarrierLegalCompliance', to='core.Requirement'),
        ),
        migrations.AlterField(
            model_name='carrierlegalcompliance',
            name='requirement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_requirement', to='core.Requirement'),
        ),
    ]
