# Generated by Django 2.2 on 2019-04-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190415_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='requirements',
            field=models.ManyToManyField(default=0, related_name='driver_requirements', through='core.DriverRequirement', to='core.Requirement'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='requirements',
            field=models.ManyToManyField(default=0, related_name='vehicle_requirements', through='core.VehicleEquipment', to='core.Requirement'),
        ),
        migrations.AlterField(
            model_name='driverrequirement',
            name='requirement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='driver_requirement', to='core.Requirement'),
        ),
        migrations.AlterField(
            model_name='vehicleequipment',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requirement', to='core.Requirement'),
        ),
    ]
